/* AstroScape — текстовая база толкования.
   Фрагменты-кирпичики: ключевые слова планет, знаков, домов, значения аспектов и
   достоинств. Движок (js/interp.js) собирает из них фразы по шаблонам.
   Все ключевые слова стоят в именительном падеже, а шаблоны построены через
   тире и двоеточие: так фраза собирается без согласований и не ломает язык.
   Тексты описательные: это язык символов, а не предсказание событий.
   Языки без своей базы берут английскую. */
(function (NS) {
  'use strict';

  NS.TEXTS = {
    ru: {
      // короткие, без внутреннего «и»: они подставляются в перечисления
      planet: {
        Sun: 'воля', Moon: 'настроение', Mercury: 'мысль', Venus: 'согласие',
        Mars: 'действие', Jupiter: 'рост', Saturn: 'порядок',
        Uranus: 'неожиданность', Neptune: 'воображение', Pluto: 'глубина',
      },
      sign: {
        0: 'прямой натиск', 1: 'спокойная основательность', 2: 'любопытство и лёгкость',
        3: 'забота и память', 4: 'щедрость и заметность', 5: 'разбор и точность',
        6: 'равновесие и согласие', 7: 'глубина и упорство', 8: 'размах и поиск смысла',
        9: 'выдержка и расчёт', 10: 'независимость и новизна', 11: 'отзывчивость и текучесть',
      },
      house: {
        1: 'облик и первый шаг', 2: 'своё и надёжное', 3: 'разговоры и ближний круг',
        4: 'дом и корни', 5: 'игра и творчество', 6: 'работа и распорядок',
        7: 'другой человек и договор', 8: 'общее и глубинное', 9: 'дальнее и взгляд на мир',
        10: 'дело и репутация', 11: 'круг людей и замыслы', 12: 'тишина и внутреннее',
      },
      aspect: {
        0: 'действуют заодно и усиливают друг друга',
        1: 'тянут в разные стороны, нужен баланс',
        2: 'поддерживают друг друга, выходит легко',
        3: 'спорят между собой, нужно усилие',
        4: 'дают возможность, если сделать шаг',
      },
      dign: {
        domicile: 'знак обители: действует свободно и уверенно',
        exalt: 'знак экзальтации: качества звучат ярче обычного',
        detriment: 'знак изгнания: приходится действовать чужими средствами',
        fall: 'знак падения: проявиться прямо трудно, нужна опора',
      },
      moonPhase: {
        0: 'Новолуние: начало круга, замыслы ещё без формы.',
        1: 'Растущий серп: первые шаги, всё только набирает силу.',
        2: 'Первая четверть: замысел встречает сопротивление, нужен нажим.',
        3: 'Луна почти полная: дело разворачивается и становится заметным.',
        4: 'Полнолуние: всё видно ясно, противоположности сходятся лицом к лицу.',
        5: 'Убывающая Луна: время отдавать и делиться сделанным.',
        6: 'Последняя четверть: поворот к разбору, лишнее отпадает.',
        7: 'Старая Луна: тишина перед новым кругом, хорошее время закончить.',
      },
      tpl: {
        moonSign: 'Луна в знаке {sign}: настроение дня — {signKw}.',
        moonHouse: 'Луна в {house} доме: в фокусе — {houseKw}.',
        sunSign: 'Солнце в знаке {sign}: на первом плане — {signKw}.',
        sunHouse: 'Солнце в {house} доме: главная область — {houseKw}.',
        aspect: '{a} и {b} {meaning} — {phase}. Здесь встречаются {aKw} и {bKw}.',
        dignity: '{planet} в знаке {sign} — {meaning}.',
        retro: '{planet} ретрограден: {planetKw} — не для разгона, а для пересмотра.',
        angular: '{planet} у угла карты ({angle}): на видном месте — {planetKw}.',
        hour: 'Час {planet}: тон ближайшего часа — {planetKw}.',
        voidMoon: 'Луна без курса до {t}: начатое сейчас легко повисает, лучше завершать старое.',
        moonNext: 'Ближайшее событие: Луна {sym} {planet} ({asp}) в {t}.',
        ingress: '{planet} переходит в знак {sign} {when}: тон меняется на {signKw}.',
        station: '{planet} {dir} {when}: движение останавливается и поворачивает.',
        eclipseSun: 'Солнечное затмение {when}: узел круга, время само подводит итоги.',
        eclipseMoon: 'Лунное затмение {when}: скрытое выходит наружу.',
        lead: '{phase} · {moonSign} · {chart} · час {hourRuler}',
      },
      angleName: { 1: 'асцендент', 4: 'надир', 7: 'десцендент', 10: 'середина неба' },
      phase2: { applying: 'аспект сходится', separating: 'аспект расходится' },
      dirWord: { toRetro: 'разворачивается на ретроградное движение', toDirect: 'возвращается к прямому движению' },
      whenWord: { today: 'сегодня', tomorrow: 'завтра', inDays: 'через {n} дн.' },
      note: 'Толкование собрано по правилам из положения светил. Это язык символов, а не прогноз событий.',
    },

    en: {
      planet: {
        Sun: 'will', Moon: 'mood', Mercury: 'thought', Venus: 'accord',
        Mars: 'action', Jupiter: 'growth', Saturn: 'order',
        Uranus: 'surprise', Neptune: 'imagination', Pluto: 'depth',
      },
      sign: {
        0: 'direct push', 1: 'calm solidity', 2: 'curiosity and lightness',
        3: 'care and memory', 4: 'warmth and visibility', 5: 'sorting and precision',
        6: 'balance and accord', 7: 'depth and persistence', 8: 'scope and a search for meaning',
        9: 'endurance and calculation', 10: 'independence and novelty', 11: 'sensitivity and flow',
      },
      house: {
        1: 'appearance and the first move', 2: 'what is yours and steady', 3: 'talk and the near circle',
        4: 'home and roots', 5: 'play and making things', 6: 'work and routine',
        7: 'the other person and agreements', 8: 'shared and deep matters', 9: 'distance and outlook',
        10: 'work in the world and standing', 11: 'circles of people and plans', 12: 'quiet and inner life',
      },
      aspect: {
        0: 'act as one and strengthen each other',
        1: 'pull opposite ways and ask for balance',
        2: 'support each other, things come easily',
        3: 'argue with each other, effort is needed',
        4: 'offer an opening if you take a step',
      },
      dign: {
        domicile: 'sign of domicile: it acts freely and surely',
        exalt: 'sign of exaltation: its qualities ring louder than usual',
        detriment: 'sign of detriment: it works with borrowed means',
        fall: 'sign of fall: hard to show directly, support is needed',
      },
      moonPhase: {
        0: 'New Moon: the circle begins, ideas have no shape yet.',
        1: 'Waxing crescent: first steps, everything is gathering strength.',
        2: 'First quarter: the idea meets resistance and needs pressure.',
        3: 'Waxing gibbous: the matter unfolds and becomes visible.',
        4: 'Full Moon: everything is plain to see, opposites meet face to face.',
        5: 'Waning gibbous: a time to give and share what was made.',
        6: 'Last quarter: a turn towards sorting, the surplus falls away.',
        7: 'Old Moon: quiet before a new circle, a good time to finish.',
      },
      tpl: {
        moonSign: 'Moon in {sign}: the mood of the day — {signKw}.',
        moonHouse: 'Moon in house {house}: in focus — {houseKw}.',
        sunSign: 'Sun in {sign}: front and centre — {signKw}.',
        sunHouse: 'Sun in house {house}: the main field — {houseKw}.',
        aspect: '{a} and {b} {meaning} — {phase}. Here {aKw} meets {bKw}.',
        dignity: '{planet} in {sign} — {meaning}.',
        retro: '{planet} is retrograde: {planetKw} — for review rather than for speed.',
        angular: '{planet} at an angle of the chart ({angle}): in plain view — {planetKw}.',
        hour: 'Hour of {planet}: the tone of the coming hour — {planetKw}.',
        voidMoon: 'Moon void of course until {t}: what starts now tends to hang — better to finish old things.',
        moonNext: 'Next event: Moon {sym} {planet} ({asp}) at {t}.',
        ingress: '{planet} enters {sign} {when}: the tone shifts to {signKw}.',
        station: '{planet} {dir} {when}: the motion halts and turns.',
        eclipseSun: 'Solar eclipse {when}: a knot of the cycle, time draws its own conclusions.',
        eclipseMoon: 'Lunar eclipse {when}: what was hidden comes out.',
        lead: '{phase} · {moonSign} · {chart} · hour of {hourRuler}',
      },
      angleName: { 1: 'ascendant', 4: 'nadir', 7: 'descendant', 10: 'midheaven' },
      phase2: { applying: 'applying', separating: 'separating' },
      dirWord: { toRetro: 'turns retrograde', toDirect: 'turns direct' },
      whenWord: { today: 'today', tomorrow: 'tomorrow', inDays: 'in {n} days' },
      note: 'This reading is assembled by rules from the positions of the bodies. It is a language of symbols, not a forecast of events.',
    },


    de: {
      planet: {
        Sun: 'Wille', Moon: 'Stimmung', Mercury: 'Gedanke', Venus: 'Einklang', Mars: 'Tat',
        Jupiter: 'Wachstum', Saturn: 'Ordnung', Uranus: 'Überraschung', Neptune: 'Vorstellung', Pluto: 'Tiefe',
      },
      sign: {
        0: 'direkter Vorstoß', 1: 'ruhige Beständigkeit', 2: 'Neugier und Leichtigkeit',
        3: 'Fürsorge und Erinnerung', 4: 'Großzügigkeit und Sichtbarkeit', 5: 'Sichtung und Genauigkeit',
        6: 'Gleichgewicht und Einklang', 7: 'Tiefe und Beharrlichkeit', 8: 'Weite und Sinnsuche',
        9: 'Ausdauer und Berechnung', 10: 'Unabhängigkeit und Neuheit', 11: 'Empfindsamkeit und Fluss',
      },
      house: {
        1: 'Auftreten und erster Schritt', 2: 'das Eigene und Verlässliche', 3: 'Gespräche und naher Kreis',
        4: 'Zuhause und Wurzeln', 5: 'Spiel und Schöpfung', 6: 'Arbeit und Tagesordnung',
        7: 'der andere Mensch und Abmachungen', 8: 'Gemeinsames und Tiefliegendes', 9: 'Ferne und Weltsicht',
        10: 'Werk und Ansehen', 11: 'Menschenkreis und Vorhaben', 12: 'Stille und Inneres',
      },
      aspect: {
        0: 'wirken gemeinsam und verstärken einander', 1: 'ziehen in verschiedene Richtungen, Ausgleich ist nötig', 2: 'stützen einander, es geht leicht',
        3: 'streiten miteinander, es braucht Kraft', 4: 'bieten eine Gelegenheit, wenn man einen Schritt tut',
      },
      dign: {
        domicile: 'Zeichen des Domizils: handelt frei und sicher',
        exalt: 'Zeichen der Erhöhung: die Eigenschaften klingen lauter als sonst',
        detriment: 'Zeichen des Exils: es muss mit fremden Mitteln handeln',
        fall: 'Zeichen des Falls: es zeigt sich schwer direkt, Halt ist nötig',
      },
      moonPhase: {
        0: 'Neumond: der Kreis beginnt, die Gedanken haben noch keine Form.',
        1: 'Zunehmende Sichel: erste Schritte, alles sammelt Kraft.',
        2: 'Erstes Viertel: der Plan stößt auf Widerstand und braucht Druck.',
        3: 'Zunehmender Mond: die Sache entfaltet sich und wird sichtbar.',
        4: 'Vollmond: alles liegt offen, Gegensätze stehen sich gegenüber.',
        5: 'Abnehmender Mond: Zeit zu geben und zu teilen, was entstanden ist.',
        6: 'Letztes Viertel: Wendung zum Sichten, Überflüssiges fällt ab.',
        7: 'Alter Mond: Stille vor dem neuen Kreis, eine gute Zeit zum Abschließen.',
      },
      tpl: {
        moonSign: 'Mond in {sign}: die Stimmung des Tages — {signKw}.',
        moonHouse: 'Mond im {house}. Haus: im Blick — {houseKw}.',
        sunSign: 'Sonne in {sign}: im Vordergrund — {signKw}.',
        sunHouse: 'Sonne im {house}. Haus: das Hauptfeld — {houseKw}.',
        aspect: '{a} und {b} {meaning} — {phase}. Hier treffen sich {aKw} und {bKw}.',
        dignity: '{planet} in {sign} — {meaning}.',
        retro: '{planet} ist rückläufig: {planetKw} — zum Überprüfen, nicht zum Beschleunigen.',
        angular: '{planet} an einer Achse des Horoskops ({angle}): sichtbar wird {planetKw}.',
        hour: 'Stunde des {planet}: der Ton der nächsten Stunde — {planetKw}.',
        voidMoon: 'Mond ohne Lauf bis {t}: was jetzt beginnt, bleibt leicht hängen — besser Altes abschließen.',
        moonNext: 'Nächstes Ereignis: Mond {sym} {planet} ({asp}) um {t}.',
        ingress: '{planet} wechselt {when} in {sign}: der Ton wird zu {signKw}.',
        station: '{planet} {dir} {when}: die Bewegung hält an und kehrt um.',
        eclipseSun: 'Sonnenfinsternis {when}: ein Knoten des Zyklus, die Zeit zieht Bilanz.',
        eclipseMoon: 'Mondfinsternis {when}: Verborgenes tritt hervor.',
        lead: '{phase} · {moonSign} · {chart} · Stunde des {hourRuler}',
      },
      angleName: { 1: 'Aszendent', 4: 'Imum Coeli', 7: 'Deszendent', 10: 'Medium Coeli' },
      phase2: { applying: 'Aspekt läuft zu', separating: 'Aspekt läuft aus' },
      dirWord: { toRetro: 'wird rückläufig', toDirect: 'wird wieder direktläufig' },
      whenWord: { today: 'heute', tomorrow: 'morgen', inDays: 'in {n} Tagen' },
    },

    es: {
      planet: {
        Sun: 'voluntad', Moon: 'ánimo', Mercury: 'pensamiento', Venus: 'acuerdo', Mars: 'acción',
        Jupiter: 'crecimiento', Saturn: 'orden', Uranus: 'sorpresa', Neptune: 'imaginación', Pluto: 'profundidad',
      },
      sign: {
        0: 'empuje directo', 1: 'solidez tranquila', 2: 'curiosidad y ligereza',
        3: 'cuidado y memoria', 4: 'generosidad y presencia', 5: 'análisis y precisión',
        6: 'equilibrio y acuerdo', 7: 'profundidad y tenacidad', 8: 'amplitud y búsqueda de sentido',
        9: 'aguante y cálculo', 10: 'independencia y novedad', 11: 'sensibilidad y fluidez',
      },
      house: {
        1: 'la apariencia y el primer paso', 2: 'lo propio y lo seguro', 3: 'las conversaciones y el círculo cercano',
        4: 'la casa y las raíces', 5: 'el juego y la creación', 6: 'el trabajo y la rutina',
        7: 'la otra persona y los acuerdos', 8: 'lo común y lo profundo', 9: 'la distancia y la visión del mundo',
        10: 'la obra y la reputación', 11: 'el círculo de gente y los planes', 12: 'el silencio y lo interior',
      },
      aspect: {
        0: 'actúan al unísono y se refuerzan', 1: 'tiran en direcciones opuestas y piden equilibrio', 2: 'se apoyan, todo sale con facilidad',
        3: 'discuten entre sí, hace falta esfuerzo', 4: 'ofrecen una oportunidad si das un paso',
      },
      dign: {
        domicile: 'signo de domicilio: actúa libre y con seguridad',
        exalt: 'signo de exaltación: sus cualidades suenan más fuerte que de costumbre',
        detriment: 'signo de exilio: tiene que actuar con medios ajenos',
        fall: 'signo de caída: le cuesta mostrarse directamente, necesita apoyo',
      },
      moonPhase: {
        0: 'Luna nueva: empieza el ciclo, las ideas aún no tienen forma.',
        1: 'Creciente: primeros pasos, todo va tomando fuerza.',
        2: 'Cuarto creciente: la idea encuentra resistencia y pide empuje.',
        3: 'Luna gibosa creciente: el asunto se despliega y se hace visible.',
        4: 'Luna llena: todo se ve con claridad, los opuestos se miran de frente.',
        5: 'Luna gibosa menguante: tiempo de dar y compartir lo hecho.',
        6: 'Cuarto menguante: giro hacia la revisión, lo sobrante se cae.',
        7: 'Luna vieja: silencio antes del nuevo ciclo, buen momento para terminar.',
      },
      tpl: {
        moonSign: 'Luna en {sign}: el ánimo del día — {signKw}.',
        moonHouse: 'Luna en la casa {house}: en foco — {houseKw}.',
        sunSign: 'Sol en {sign}: en primer plano — {signKw}.',
        sunHouse: 'Sol en la casa {house}: el campo principal — {houseKw}.',
        aspect: '{a} y {b} {meaning} — {phase}. Aquí se encuentran {aKw} y {bKw}.',
        dignity: '{planet} en {sign} — {meaning}.',
        retro: '{planet} está retrógrado: {planetKw} — para revisar, no para acelerar.',
        angular: '{planet} en un ángulo de la carta ({angle}): a la vista — {planetKw}.',
        hour: 'Hora de {planet}: el tono de la próxima hora — {planetKw}.',
        voidMoon: 'Luna fuera de curso hasta {t}: lo que empieza ahora queda en el aire — mejor cerrar lo viejo.',
        moonNext: 'Próximo evento: Luna {sym} {planet} ({asp}) a las {t}.',
        ingress: '{planet} entra en {sign} {when}: el tono cambia a {signKw}.',
        station: '{planet} {dir} {when}: el movimiento se detiene y gira.',
        eclipseSun: 'Eclipse de Sol {when}: un nudo del ciclo, el tiempo hace su balance.',
        eclipseMoon: 'Eclipse de Luna {when}: lo oculto sale a la luz.',
        lead: '{phase} · {moonSign} · {chart} · hora de {hourRuler}',
      },
      angleName: { 1: 'ascendente', 4: 'fondo del cielo', 7: 'descendente', 10: 'medio cielo' },
      phase2: { applying: 'aspecto aplicativo', separating: 'aspecto separativo' },
      dirWord: { toRetro: 'se vuelve retrógrado', toDirect: 'vuelve a ser directo' },
      whenWord: { today: 'hoy', tomorrow: 'mañana', inDays: 'en {n} días' },
    },

    fr: {
      planet: {
        Sun: 'volonté', Moon: 'humeur', Mercury: 'pensée', Venus: 'accord', Mars: 'action',
        Jupiter: 'croissance', Saturn: 'ordre', Uranus: 'surprise', Neptune: 'imagination', Pluto: 'profondeur',
      },
      sign: {
        0: 'élan direct', 1: 'solidité tranquille', 2: 'curiosité et légèreté',
        3: 'soin et mémoire', 4: 'générosité et présence', 5: 'tri et précision',
        6: 'équilibre et accord', 7: 'profondeur et ténacité', 8: 'ampleur et quête de sens',
        9: 'endurance et calcul', 10: 'indépendance et nouveauté', 11: 'sensibilité et fluidité',
      },
      house: {
        1: 'l’allure et le premier pas', 2: 'ce qui est à soi et sûr', 3: 'les échanges et le cercle proche',
        4: 'la maison et les racines', 5: 'le jeu et la création', 6: 'le travail et le rythme',
        7: 'l’autre et les accords', 8: 'le commun et le profond', 9: 'le lointain et la vision du monde',
        10: 'l’œuvre et la réputation', 11: 'le cercle de gens et les projets', 12: 'le silence et l’intérieur',
      },
      aspect: {
        0: 'agissent de concert et se renforcent', 1: 'tirent en sens contraire et demandent un équilibre', 2: 'se soutiennent, cela vient facilement',
        3: 'se contredisent, un effort est nécessaire', 4: 'offrent une ouverture si l’on fait un pas',
      },
      dign: {
        domicile: 'signe de domicile : elle agit librement et sûrement',
        exalt: 'signe d’exaltation : ses qualités sonnent plus fort que d’ordinaire',
        detriment: 'signe d’exil : elle doit agir avec des moyens empruntés',
        fall: 'signe de chute : difficile de se montrer directement, un appui est nécessaire',
      },
      moonPhase: {
        0: 'Nouvelle Lune : le cycle commence, les idées n’ont pas encore de forme.',
        1: 'Premier croissant : premiers pas, tout prend des forces.',
        2: 'Premier quartier : l’idée rencontre une résistance et demande de la pression.',
        3: 'Lune gibbeuse croissante : l’affaire se déploie et devient visible.',
        4: 'Pleine Lune : tout est visible, les contraires se font face.',
        5: 'Lune gibbeuse décroissante : temps de donner et de partager ce qui a été fait.',
        6: 'Dernier quartier : virage vers le tri, le superflu tombe.',
        7: 'Vieille Lune : silence avant le nouveau cycle, bon moment pour finir.',
      },
      tpl: {
        moonSign: 'Lune en {sign} : l’humeur du jour — {signKw}.',
        moonHouse: 'Lune en maison {house} : au centre — {houseKw}.',
        sunSign: 'Soleil en {sign} : au premier plan — {signKw}.',
        sunHouse: 'Soleil en maison {house} : le champ principal — {houseKw}.',
        aspect: '{a} et {b} {meaning} — {phase}. Ici se rencontrent {aKw} et {bKw}.',
        dignity: '{planet} en {sign} — {meaning}.',
        retro: '{planet} est rétrograde : {planetKw} — pour revoir, non pour accélérer.',
        angular: '{planet} à un angle du thème ({angle}) : bien en vue — {planetKw}.',
        hour: 'Heure de {planet} : le ton de l’heure qui vient — {planetKw}.',
        voidMoon: 'Lune hors course jusqu’à {t} : ce qui commence maintenant reste en suspens — mieux vaut finir l’ancien.',
        moonNext: 'Prochain événement : Lune {sym} {planet} ({asp}) à {t}.',
        ingress: '{planet} entre en {sign} {when} : le ton passe à {signKw}.',
        station: '{planet} {dir} {when} : le mouvement s’arrête et se retourne.',
        eclipseSun: 'Éclipse de Soleil {when} : un nœud du cycle, le temps fait ses comptes.',
        eclipseMoon: 'Éclipse de Lune {when} : ce qui était caché apparaît.',
        lead: '{phase} · {moonSign} · {chart} · heure de {hourRuler}',
      },
      angleName: { 1: 'ascendant', 4: 'fond du ciel', 7: 'descendant', 10: 'milieu du ciel' },
      phase2: { applying: 'aspect applicatif', separating: 'aspect séparatif' },
      dirWord: { toRetro: 'devient rétrograde', toDirect: 'redevient direct' },
      whenWord: { today: 'aujourd’hui', tomorrow: 'demain', inDays: 'dans {n} jours' },
    },

    it: {
      planet: {
        Sun: 'volontà', Moon: 'umore', Mercury: 'pensiero', Venus: 'accordo', Mars: 'azione',
        Jupiter: 'crescita', Saturn: 'ordine', Uranus: 'sorpresa', Neptune: 'immaginazione', Pluto: 'profondità',
      },
      sign: {
        0: 'slancio diretto', 1: 'solidità tranquilla', 2: 'curiosità e leggerezza',
        3: 'cura e memoria', 4: 'generosità e presenza', 5: 'selezione e precisione',
        6: 'equilibrio e accordo', 7: 'profondità e tenacia', 8: 'ampiezza e ricerca di senso',
        9: 'tenuta e calcolo', 10: 'indipendenza e novità', 11: 'sensibilità e fluidità',
      },
      house: {
        1: 'l’aspetto e il primo passo', 2: 'ciò che è proprio e sicuro', 3: 'i discorsi e la cerchia vicina',
        4: 'la casa e le radici', 5: 'il gioco e la creazione', 6: 'il lavoro e la routine',
        7: 'l’altra persona e gli accordi', 8: 'il comune e il profondo', 9: 'la lontananza e la visione del mondo',
        10: 'l’opera e la reputazione', 11: 'la cerchia di persone e i progetti', 12: 'il silenzio e l’interiorità',
      },
      aspect: {
        0: 'agiscono all’unisono e si rafforzano', 1: 'tirano in direzioni opposte e chiedono equilibrio', 2: 'si sostengono, viene facile',
        3: 'si contraddicono, serve sforzo', 4: 'offrono un’occasione se fai un passo',
      },
      dign: {
        domicile: 'segno di domicilio: agisce libera e sicura',
        exalt: 'segno di esaltazione: le sue qualità suonano più forte del solito',
        detriment: 'segno di esilio: deve agire con mezzi altrui',
        fall: 'segno di caduta: fatica a mostrarsi direttamente, serve appoggio',
      },
      moonPhase: {
        0: 'Luna nuova: il ciclo comincia, le idee non hanno ancora forma.',
        1: 'Luna crescente: primi passi, tutto prende forza.',
        2: 'Primo quarto: l’idea incontra resistenza e chiede spinta.',
        3: 'Gibbosa crescente: la faccenda si apre e diventa visibile.',
        4: 'Luna piena: tutto è chiaro, gli opposti si guardano in faccia.',
        5: 'Gibbosa calante: tempo di dare e condividere ciò che è stato fatto.',
        6: 'Ultimo quarto: svolta verso la selezione, il superfluo cade.',
        7: 'Luna vecchia: silenzio prima del nuovo ciclo, buon momento per finire.',
      },
      tpl: {
        moonSign: 'Luna in {sign}: l’umore del giorno — {signKw}.',
        moonHouse: 'Luna in casa {house}: al centro — {houseKw}.',
        sunSign: 'Sole in {sign}: in primo piano — {signKw}.',
        sunHouse: 'Sole in casa {house}: il campo principale — {houseKw}.',
        aspect: '{a} e {b} {meaning} — {phase}. Qui si incontrano {aKw} e {bKw}.',
        dignity: '{planet} in {sign} — {meaning}.',
        retro: '{planet} è retrogrado: {planetKw} — per rivedere, non per accelerare.',
        angular: '{planet} a un angolo del tema ({angle}): in vista — {planetKw}.',
        hour: 'Ora di {planet}: il tono dell’ora che viene — {planetKw}.',
        voidMoon: 'Luna fuori corso fino alle {t}: ciò che inizia ora resta sospeso — meglio chiudere il vecchio.',
        moonNext: 'Prossimo evento: Luna {sym} {planet} ({asp}) alle {t}.',
        ingress: '{planet} entra in {sign} {when}: il tono passa a {signKw}.',
        station: '{planet} {dir} {when}: il moto si ferma e gira.',
        eclipseSun: 'Eclissi di Sole {when}: un nodo del ciclo, il tempo tira le somme.',
        eclipseMoon: 'Eclissi di Luna {when}: ciò che era nascosto viene fuori.',
        lead: '{phase} · {moonSign} · {chart} · ora di {hourRuler}',
      },
      angleName: { 1: 'ascendente', 4: 'fondo cielo', 7: 'discendente', 10: 'medio cielo' },
      phase2: { applying: 'aspetto applicativo', separating: 'aspetto separativo' },
      dirWord: { toRetro: 'diventa retrogrado', toDirect: 'torna diretto' },
      whenWord: { today: 'oggi', tomorrow: 'domani', inDays: 'tra {n} giorni' },
    },

    pt: {
      planet: {
        Sun: 'vontade', Moon: 'ânimo', Mercury: 'pensamento', Venus: 'acordo', Mars: 'ação',
        Jupiter: 'crescimento', Saturn: 'ordem', Uranus: 'surpresa', Neptune: 'imaginação', Pluto: 'profundidade',
      },
      sign: {
        0: 'impulso directo', 1: 'solidez tranquila', 2: 'curiosidade e leveza',
        3: 'cuidado e memória', 4: 'generosidade e presença', 5: 'triagem e precisão',
        6: 'equilíbrio e acordo', 7: 'profundidade e tenacidade', 8: 'amplitude e procura de sentido',
        9: 'resistência e cálculo', 10: 'independência e novidade', 11: 'sensibilidade e fluidez',
      },
      house: {
        1: 'a aparência e o primeiro passo', 2: 'o que é seu e seguro', 3: 'as conversas e o círculo próximo',
        4: 'a casa e as raízes', 5: 'o jogo e a criação', 6: 'o trabalho e a rotina',
        7: 'a outra pessoa e os acordos', 8: 'o comum e o profundo', 9: 'a distância e a visão do mundo',
        10: 'a obra e a reputação', 11: 'o círculo de pessoas e os planos', 12: 'o silêncio e o interior',
      },
      aspect: {
        0: 'agem em conjunto e reforçam-se', 1: 'puxam em sentidos opostos e pedem equilíbrio', 2: 'apoiam-se, tudo sai com facilidade',
        3: 'contradizem-se, é preciso esforço', 4: 'abrem uma oportunidade se deres um passo',
      },
      dign: {
        domicile: 'signo de domicílio: age livre e com segurança',
        exalt: 'signo de exaltação: as suas qualidades soam mais alto do que é habitual',
        detriment: 'signo de exílio: tem de agir com meios alheios',
        fall: 'signo de queda: custa-lhe mostrar-se directamente, precisa de apoio',
      },
      moonPhase: {
        0: 'Lua nova: o ciclo começa, as ideias ainda não têm forma.',
        1: 'Lua crescente: primeiros passos, tudo ganha força.',
        2: 'Quarto crescente: a ideia encontra resistência e pede impulso.',
        3: 'Lua gibosa crescente: o assunto desenrola-se e torna-se visível.',
        4: 'Lua cheia: tudo se vê com clareza, os opostos olham-se de frente.',
        5: 'Lua gibosa minguante: tempo de dar e partilhar o que foi feito.',
        6: 'Quarto minguante: viragem para a triagem, o supérfluo cai.',
        7: 'Lua velha: silêncio antes do novo ciclo, bom momento para terminar.',
      },
      tpl: {
        moonSign: 'Lua em {sign}: o ânimo do dia — {signKw}.',
        moonHouse: 'Lua na casa {house}: em foco — {houseKw}.',
        sunSign: 'Sol em {sign}: em primeiro plano — {signKw}.',
        sunHouse: 'Sol na casa {house}: o campo principal — {houseKw}.',
        aspect: '{a} e {b} {meaning} — {phase}. Aqui encontram-se {aKw} e {bKw}.',
        dignity: '{planet} em {sign} — {meaning}.',
        retro: '{planet} está retrógrado: {planetKw} — para rever, não para acelerar.',
        angular: '{planet} num ângulo do mapa ({angle}): à vista — {planetKw}.',
        hour: 'Hora de {planet}: o tom da próxima hora — {planetKw}.',
        voidMoon: 'Lua fora de curso até às {t}: o que começa agora fica no ar — melhor fechar o antigo.',
        moonNext: 'Próximo evento: Lua {sym} {planet} ({asp}) às {t}.',
        ingress: '{planet} entra em {sign} {when}: o tom passa a {signKw}.',
        station: '{planet} {dir} {when}: o movimento pára e vira.',
        eclipseSun: 'Eclipse do Sol {when}: um nó do ciclo, o tempo faz as contas.',
        eclipseMoon: 'Eclipse da Lua {when}: o que estava escondido vem ao de cima.',
        lead: '{phase} · {moonSign} · {chart} · hora de {hourRuler}',
      },
      angleName: { 1: 'ascendente', 4: 'fundo do céu', 7: 'descendente', 10: 'meio do céu' },
      phase2: { applying: 'aspecto aplicativo', separating: 'aspecto separativo' },
      dirWord: { toRetro: 'fica retrógrado', toDirect: 'volta a directo' },
      whenWord: { today: 'hoje', tomorrow: 'amanhã', inDays: 'daqui a {n} dias' },
    },
  };
})(window.AstroScape);
